
Resources:
  EC2SecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
        GroupDescription: Allow http to client host 
        SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0 
  Ec2Instance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t2.micro
      ImageId: ami-04bf6dcdc9ab498ca # Amazon Linux AMI in N.California
      UserData:
        'Fn::Base64': 
          !Sub |
            #!/bin/bash
            yum -y update

            # install apache
            yum install httpd24 -y  

            # start server
            service httpd start
            chkconfig httpd on
      SecurityGroups:
        - !Ref EC2SecurityGroup 
      Tags:
        - Key: Name
          Value: My EC2 Instance
        - Key: Type
          Value: Worker Instancess
#When you specify a parameter's logical name, it returns the value of the parameter.

#When you specify a resource's logical name, it returns a value that you can typically use to refer to that resource, such as a physical ID.